### ISSUE TITLE
Build your own variation of clicker app

### ISSUE THREAD

**Issue by saurabhnative** [saurabhnative/react30_2_clickerapp#1]
Modify the CSS or the base code to build your own version of clicker app.
Submissions by multiple contributors to this issue are allowed.
Steps to contribute:
1. Comment on this issue if you are interested in building your own version
2. Wait for being assigned to the issue and getting solution number
3. Once solution number is assigned, clone the repository and create a folder `solution_[your_assigned_number]` in the repo.
    For example if `solution_3` is assigned to you then you need to create a folder `solution_3` in this repo.
4. If you are a beginner who would only like to modify CSS then copy the code from `solution_1` folder into your assigned folder. If you know react and want to build your own solution then copy the code from `1_starter_code` into your assigned folder.
5. Once finished submit your solution as pull request to this repository. 

Note: No pull request will be accepted until you are added as an assignee to this issue.

**Comment by Harshit107** [comment]
Hi, I want to modify it

**Comment by saurabhnative** [comment]
@Harshit107 You have been assigned the issue and can submit your modified version in `solution_2` folder.
Let me know if you need any help.

**Comment by ellu-laitinen** [comment]
Hi, I would like to do this as well.

**Comment by saurabhnative** [comment]
@ellu-laitinen  You have been assigned the issue and can submit your modified version in `solution_3` folder.
Let me know if you need any help.

**Comment by abhinavvv-7** [comment]
I would like to modify it
