### ISSUE TITLE
Add learning resources to README file

### ISSUE THREAD

**Issue by saurabhnative** [saurabhnative/react30_2_clickerapp#2]
Add learning resources in README.md section related to `useState` hook.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.

**Comment by bhawesh96** [comment]
@codeclassifiers , I'd like to take this up.

**Comment by saurabhnative** [comment]
@bhawesh96 Sure. There are some learning resources already added. So fork the latest version from master and then you can your own resources below the existing ones.

**Comment by ghostmaulik** [comment]
@codeclassifiers, would love to add some resources :)

**Comment by abhinavvv-7** [comment]
@codeclassifiers , I'd like to take this up.

**Comment by abhinavvv-7** [comment]
added an articles on hooks

**Comment by omkar669** [comment]
Hello, I would like to contribute. May I be assigned to this? 
There are some articles I would like to add to it

**Comment by saurabhnative** [comment]
@omkar669 Your pull request is merged with relevant Hacktoberfest labels

**Comment by saurabhnative** [comment]
@ghostmaulik  Your pull request is merged with relevant Hacktoberfest labels
