### ISSUE TITLE
Add learning reasourse to README File

### ISSUE THREAD

**Issue by ANISHA-C-MENON** [saurabhnative/react30_2_clickerapp#20]
Hi @codeclassifiers I would like to contribute to you. Could you please assign it to me?

**Comment by saurabhnative** [comment]
@ANISHA-C-MENON You have been added as an assignee. Feel free to submit pull request to this repository.

**Comment by BIDISHA-CHANDA** [comment]
@saurabhnative Hello,I would like to contribute.May I be assigned to this?

**Comment by ayushi2410** [comment]
@saurabhnative I would like to contribute.May I be assigned to this?

**Comment by saurabhnative** [comment]
@ayushi2410 Yes you can contribute to this issue
